### ISSUE TITLE
Build error with 5.0.1

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKIOMeshSTL#29]
```text
Creating library C:/Libs/ITK-5.0.1-vs2015/lib/Debug/itkIOMeshSTL-5.0.lib and object C:/Libs/ITK-5.0.1-vs2015/lib/Debug/itkIOMeshSTL-5.0.exp
3>itkSTLMeshIO.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __cdecl itk::MeshIOBase::SetPointComponentType(enum itk::MeshIOBase::IOComponentType)" (__imp_?SetPointComponentType@MeshIOBase@itk@@UEAAXW4IOComponentType@12@@Z) referenced in function "protected: __cdecl itk::STLMeshIO::STLMeshIO(void)" (??0STLMeshIO@itk@@IEAA@XZ)
```
[Output-Build.txt](https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL/files/3488044/Output-Build.txt)

VS2015x64, CMake 3.15.2, BUILD_SHARED_LIBS ON, and following modules enabled: IOMeshSTL, IOTransformDCMTK, ITKIODCMTK, ITKReview, ITKTBB, ITKVtkGlue and RLEImage.

The link library list is
```text
..\..\..\..\lib\Debug\ITKCommon-5.0.lib
C:\Libs\tbb2019_20190410oss\lib\intel64\vc14\tbb_debug.lib
..\..\..\..\lib\Debug\itksys-5.0.lib
ws2_32.lib
Psapi.lib
..\..\..\..\lib\Debug\ITKVNLInstantiation-5.0.lib
..\..\..\..\lib\Debug\itkvnl_algo-5.0.lib
..\..\..\..\lib\Debug\itkvnl-5.0.lib
..\..\..\..\lib\Debug\itkv3p_netlib-5.0.lib
..\..\..\..\lib\Debug\itknetlib-5.0.lib
..\..\..\..\lib\Debug\itkvcl-5.0.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
```
If I manually add `..\..\..\..\lib\Debug\ITKIOMeshBase-5.0.lib` to this list, the module compiles fine.

I cannot spot a problem with [module definition code](https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL/blob/master/itk-module.cmake).

**Comment by thewtex** [comment]
What if the library CMake configuration code:

https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL/blob/532a442cd69395a8743688f161b0e9f3bc0cad21/src/CMakeLists.txt#L6-L9

is updated to use `itk_module_add_library`?

https://github.com/InsightSoftwareConsortium/ITK/blob/bccf5544c9a689bb70ddfc228da68734f9c54052/Modules/IO/MeshBase/src/CMakeLists.txt#L8
