### ISSUE TITLE
Pip cannot find OSX 11.0+ versions

### ISSUE THREAD

**Issue by dmwelch** [InsightSoftwareConsortium/ITKIOMeshSTL#41]
Hi team, 

On OSX, `python3  -m pip install itk-iomeshstl` returns with:

> ERROR: Could not find a version that satisfies the requirement itk-iomeshstl (from versions: none)
> ERROR: No matching distribution found for itk-iomeshstl

Python 3.9, pip 21.1.1

**Comment by dmwelch** [comment]
`pip install git+https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL@v2.1.0#egg=itk-iomeshstl`

> Collecting itk-iomeshstl
>   Cloning https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL (to revision v2.1.0) to /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-jinhisgq/itk-iomeshstl_e5bc35da938d4f91ba139dec34750d68
>   Running command git clone -q https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-jinhisgq/itk-iomeshstl_e5bc35da938d4f91ba139dec34750d68
>   Running command git checkout -q 9c543720e5a52657b96aee78bf1e4637ff03094a
>     ERROR: Command errored out with exit status 1:
>      command: /Users/david/virtualenvs/dod/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-jinhisgq/itk-iomeshstl_e5bc35da938d4f91ba139dec34750d68/setup.py'"'"'; __file__='"'"'/private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-jinhisgq/itk-iomeshstl_e5bc35da938d4f91ba139dec34750d68/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-pip-egg-info-u9slzo4j
>          cwd: /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-jinhisgq/itk-iomeshstl_e5bc35da938d4f91ba139dec34750d68/
>     Complete output (4 lines):
>     scikit-build is required to build from source.
>     Please run:
>     
>       python -m pip install scikit-build
>     ----------------------------------------
> WARNING: Discarding git+https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL@v2.1.0#egg=itk-iomeshstl. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Could not find a version that satisfies the requirement itk-iomeshstl (unavailable) (from versions: none)
> ERROR: No matching distribution found for itk-iomeshstl (unavailable)

After installing `scikit-build`, it's complaining it cannot find my `itk` package in my current virtualenv (I use virtualenvwrapper):

> Collecting itk-iomeshstl
>   Cloning https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL (to revision v2.1.0) to /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-9h6k9ry2/itk-iomeshstl_a33bf7d07334453694201f8e3d861f48
>   Running command git clone -q https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-9h6k9ry2/itk-iomeshstl_a33bf7d07334453694201f8e3d861f48
>   Running command git checkout -q 9c543720e5a52657b96aee78bf1e4637ff03094a
>     ERROR: Command errored out with exit status 1:
>      command: /Users/david/virtualenvs/dod/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-9h6k9ry2/itk-iomeshstl_a33bf7d07334453694201f8e3d861f48/setup.py'"'"'; __file__='"'"'/private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-9h6k9ry2/itk-iomeshstl_a33bf7d07334453694201f8e3d861f48/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-pip-egg-info-0nr44p39
>          cwd: /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-install-9h6k9ry2/itk-iomeshstl_a33bf7d07334453694201f8e3d861f48/
>     Complete output (8 lines):
>     running egg_info
>     creating /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-pip-egg-info-0nr44p39/itk_iomeshstl.egg-info
>     writing /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-pip-egg-info-0nr44p39/itk_iomeshstl.egg-info/PKG-INFO
>     writing dependency_links to /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-pip-egg-info-0nr44p39/itk_iomeshstl.egg-info/dependency_links.txt
>     writing requirements to /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-pip-egg-info-0nr44p39/itk_iomeshstl.egg-info/requires.txt
>     writing top-level names to /private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-pip-egg-info-0nr44p39/itk_iomeshstl.egg-info/top_level.txt
>     writing manifest file '/private/var/folders/4m/4h6rgw0x7zb4wx7jfbv4h27c0000gn/T/pip-pip-egg-info-0nr44p39/itk_iomeshstl.egg-info/SOURCES.txt'
>     error: package directory 'itk' does not exist
>     ----------------------------------------
> WARNING: Discarding git+https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL@v2.1.0#egg=itk-iomeshstl. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Could not find a version that satisfies the requirement itk-iomeshstl (unavailable) (from versions: none)
> ERROR: No matching distribution found for itk-iomeshstl (unavailable)

**Comment by dmwelch** [comment]
Followup: it looks like the issue is that there is no Python version that supports OSX 11.0+ in pip:

```
$ pip install itk-iomeshstl
ERROR: Could not find a version that satisfies the requirement itk-iomeshstl (from versions: none)
ERROR: No matching distribution found for itk-iomeshstl

$ pip debug | grep "macosx"
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
  cp39-cp39-macosx_11_0_x86_64
  cp39-cp39-macosx_11_0_intel
  cp39-cp39-macosx_11_0_fat64
  cp39-cp39-macosx_11_0_fat32
  cp39-cp39-macosx_11_0_universal2
  cp39-cp39-macosx_11_0_universal
  cp39-cp39-macosx_10_16_x86_64
  cp39-cp39-macosx_10_16_intel
  cp39-cp39-macosx_10_16_fat64
  cp39-cp39-macosx_10_16_fat32
```

**Comment by thewtex** [comment]
@dmwelch thanks for the report. We now have wheels for Intel macosx 10.9+, Python 3.7-3.11: https://pypi.org/project/itk-iomeshstl/2.3.0/#files
